### ISSUE TITLE
Deconstruction is still oddly slow with PackedReferencePathOverlay

### ISSUE THREAD

**Issue by adamnovak** [vgteam/libbdsg#172]
@glennhickey says that, with the files in `/public/home/hickey/dev/work/chicken-pangenome/debug` on Courtyard, you can do a deconstruct run in about 32 minutes on 64 threads, including snarl build, when using the xg. But when using just the GBZ, when I od the equivalent of

```
deconstruct ./chicken-pg-sep23-new.gbz -t 64 -r ./chicken-pg-sep23-new.snarls
```

Then it crashes complaining that OpenMP can't make enough threads. When I cut the thread count to 16, it takes probably more than 2 hours.

The overlay build seems relatively fast; something important is probably still slow here and needs to be sped up. But first we need to collect actually comparable runtimes and probably profiles from two matched conditions with a consistent number of threads and a consistent choice of generating vs. loading snarls.

**Comment by adamnovak** [comment]
My 16-thread GBZ-based deconstruct eventually succeeded:

```
time vg deconstruct -v /public/home/hickey/dev/work/chicken-pangenome/debug/chicken-pg-sep23-new.gbz -t 16 -r /public/home/hickey/dev/work/chicken-pangenome/debug/chicken-pg-sep23-new.snarls >/dev/null
Computed overlay in 226.613 seconds using 2460.49 CPU seconds.
Loading snarls
Deconstructing top-level snarls

real	162m16.611s
user	2164m10.976s
sys	72m28.650s
```

**Comment by glennhickey** [comment]
My 64-thread run with xg/gbwt
```
Command being timed: "/public/home/hickey/public_html/vg.e4595514ba210f1c5ca614071e4b80cedc32ef83 deconstruct chicken-pg-sep23.xg -g chicken-pg-sep23.gbwt -t 64"
User time (seconds): 56540.98
System time (seconds): 1075.75
Percent of CPU this job got: 2986%
Elapsed (wall clock) time (h:mm:ss or m:ss): 32:09.04
```

And on GBZ
```
Command being timed: "/public/home/hickey/public_html/vg.55fd373ec93206e7b3d5e92371157b16d3e23421 deconstruct chicken-pg-sep23-new.gbz -r chicken-pg-sep23-new.snarls -t 64"
User time (seconds): 173961.51
System time (seconds): 10998.14
Percent of CPU this job got: 2362%
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:10:30
```

courtyard timings are obviously variable, but it's strange that my 64 core run was almost twice as slow as your 16 core run.  Also strange is the relative increase in system time between my two runs (10X) which is much higher than the ~4X for wall time and user time.

**Comment by glennhickey** [comment]
Oops not quite apples to apples as I used one less core but here's the time on an r4.8xlarge.  Comparable slowdown of ~3.5x to courtyard.  And still not much faster than your 16-core time which is strange since `deconstruct` should have a pretty linear speedup (barring any giant snarls that dominate everything)

xg/gbwt
```
vg deconstruct chicken-pg-sep26.xg -P galGal6 -a -r chicken-pg-sep26.snarls -g chicken-pg-sep26.gbwt -T chicken-pg-sep26.trans -t 32 | bgzip --threads 32" in 1076.8411 seconds
```

gbz
```
 vg deconstruct clip.chicken-pg-sep23-new2.gbz -P galGal6 -a -r clip.chicken-pg-sep23-new2.snarls -t 31 | bgzip --threads 31" in 3724.4324 seconds
```

**Comment by glennhickey** [comment]
On a brighter note, snarls was a bit quicker on the gbz than the xg, even with one fewer core
```
vg snarls merged.xg -T -t 32" in 459.4899 seconds
```
```
vg snarls clip.merged.gbz -T -t 31" in 417.4422 seconds
```
