### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by adamnovak** [vgteam/libbdsg#2]
Given the [many](https://github.com/stefanct/sglib) [other](https://www.sglibgames.com/) [projects](http://sg-lib.org/) using the "sglib" name, we're considering renaming this one.

Also, we have the same problem as HTSlib where we end up with `libsglib.a` and it looks silly.

Names under consideration so far include:

* **odgi**: Optimized Dynamic Graph Implementations. @ekg already has the actual odgi; we would just glom the graphs in here together with it and have one repo. The main obstacle here is that we'd have to glue the projects together, and I'm not sure if Erik wants to keep odgi separate, especially since (AFAIK) it includes that whole visualizer that wouldn't make as much sense in a graph implementation library.

**Comment by ekg** [comment]
odgi is kind of its own toolkit for graph processing (visualization being one of the cooler things it does now). I'd be more inclined to pull a bunch of graph models into it than the other direction. Thinking of names now....

**Comment by adamnovak** [comment]
We probably have some good backronyms for `libgogl` as well.

**Comment by ekg** [comment]
libosg?

It seems unique. It's in the tagline now, "optimized succinct graph" ...

**Comment by jeizenga** [comment]
I went with libbdsg.
