### ISSUE TITLE
Who are the copyright holders of this code?

### ISSUE THREAD

**Issue by mr-c** [vgteam/libbdsg#22]
A mention in the license, README, and source files would be great!

Bonus points: https://reuse.software/spec/

Thanks!

**Comment by adamnovak** [comment]
While most of the contributors are working on this project as UCSC employees (making the copyright holder probably the Regents of the University of California), we don't have any sort of copyright assignment happening, and we do have some non-UCSC contributors like @edawson. The copyright for those contributions is going to be held by either them or the person they were writing the code for as a work for hire, and they've licensed them to everyone else under the MIT license.

So the copyright holder for the project as a whole is probably the cop-out "libbdsg contributors".

**Comment by adamnovak** [comment]
Actually it's an even harder problem; I went to look at @edawson's contributions, and they're all (empty?) merge commits that came from when I ripped code out of the vg repo and preserved its history to make this repo. So some people who hold some relevant copyrights (maybe just on commit messages) might be better described as "vgteam contributors".
