### ISSUE TITLE
Vectoizable Overlays assume that graph iteration order is consistent and thus break vg pack

### ISSUE THREAD

**Issue by adamnovak** [vgteam/libbdsg#40]
The vectorizing overlays loop through all the nodes and edges in the graph, and treat that as the vectorized order.

The problem is that:

1. The overlay calls `for_each_handle` on the underlying graph twice, and assumes that the iteration order will be the same both times. If the graph doesn't have an internal concept of ordering, I'm not sure we can rely on this.

2. If you save and load the graph, the overlay will run again and create a possibly different vectorization. This causes trouble when using e.g. `vg pack` on a `HashGraph`. The pack file it produces uses the vectorization of the graph as coordinates, but next time you load the HashGraph you might not necessarily populate the hash table in the same way, and you might get a different iteration order, leading to a different vectorization.

The overlay needs to be made to always produce the same vectorization for the same graph *contents* (i.e. sort everything by node ID), or we need to bring the vectorization along with things that depend on it like pack files. Or, we need to enforce that graphs at least have a stable iteration order across serialization, even if they aren't themselves vectorizable.

@jeizenga Does this make sense to you?

**Comment by glennhickey** [comment]
I think it probably wouldn't cost much in practice to make the ranks based
on sorted ids.  A bonus would be that we could probably get the same
vectorization as xg with the overlays, so pack files would be
interchangeable between different implementations of the same graph.

**Comment by adamnovak** [comment]
OK, I will see what I can do to get a consistent vectorization.

**Comment by adamnovak** [comment]
I don't think I'll be able to always get one that matches the XG, though, since the XG is itself vectorizable and doesn't use the overlay.

**Comment by adamnovak** [comment]
OK, it looks like the way this has to work is that the minimal perfect hash function assigns us an ordering.

I can make it assign that ordering based on node IDs and orientations, instead of based on handle values, and I can make sure that the items going into the minimal perfect hash function finder are always in the same order for a given graph, and hope that that is enough to make us always get the same minimal perfect hash function for a given graph.

**Comment by ekg** [comment]
I am not certain that an identical input order to the MPHF is going to
result in the same hash function. We can check.

**Comment by glennhickey** [comment]
Yeah, there's no guarantee in the docs that you get the same hash function for identical input.  But... nothing seemed to break when I switched from STL to bbhash.  So I imagine just sorting the input vectors to the bbhash constructors would resolve the issues arising from hashgraph iteration order being random.  

Agree a thorough checking is in order.  I don't think it's the end of the world to revert to STL if there's any doubt.  Could also embed the rank explicitly in the bbhash though I'm not sure that would be any better.
