### ISSUE TITLE
Python bindings don't bind any methods that use std::vector

### ISSUE THREAD

**Issue by adamnovak** [vgteam/libbdsg#50]
It looks like @ctcisar turned off binding for `std::vector`. That makes the bindings build, but Handle Graph API methods that use `std::vector` (like `MutablePathHandleGraph::rewrite_segment`) don't get any bindings generated for them.

De-deactivating `std::vector` in `config.cfg` triggers what I think is a Binder bug, or at least an incompatibility with something in our project: https://github.com/RosettaCommons/binder/issues/100

We need to fix this, or write other API methods that let you do the same things without std::vector somehow.

**Comment by adamnovak** [comment]
@ctcisar Is this why std::vector is turned off in `config.cfg`? Do you remember if the bindings ever built with it turned on?

**Comment by ekg** [comment]
This did work for odgi's bindings

**Comment by ctcisar** [comment]
As I recall, RosettaCommons/binder#100 is the reason why I excluded it from binding.

I don't know what was causing the incompatibility, and I remember spending a while trying to troubleshoot it unsuccessfully.  I don't think I ever got libbdsg to bind with it enabled, no.

**Comment by adamnovak** [comment]
I think the ODGI bindings were done by hand and ended up with
different code being sent to pybind11 that doesn't trigger this
problem.

I'll see if I can make a small test case for the Binder folks.

**Comment by adamnovak** [comment]
OK I added what I think is a workaround for this to #49. See also: https://github.com/RosettaCommons/binder/issues/100 and https://github.com/pybind/pybind11/issues/787#issuecomment-602925116

pybind11 has magic Python list <-> `std::vector` support, but I haven't (yet?) been able to work out how to use it with Binder. So you can't do this:
```
import bdsg
g = bdsg.bdsg.HashGraph()
h = g.create_handle("GATTACA")
parts = g.divide_handle(h, [1, 3])
print(parts)
```

Instead you need to do this and manually convert to/from the generated types for different vector instantiations:
```
import bdsg
g = bdsg.bdsg.HashGraph()
h = g.create_handle("GATTACA")
v = bdsg.std.vector_unsigned_long([1, 3])
parts = g.divide_handle(h, v)
print(list(parts))
```

**Comment by ekg** [comment]
FWIW it was not very hard to hand build the bindings. And I got the
automatic conversion from std::vector to lists for free.
