### ISSUE TITLE
python documentation largely incomplete

### ISSUE THREAD

**Issue by ekg** [vgteam/libbdsg#66]
A python API documentation (on readthedoc.io) is linked to, but it's basically empty.

We might want to remove this until it's completed.

**Comment by adamnovak** [comment]
It's supposed to have autodoc-generated documentation in it, and it did when I last looked at it; something must have broken in our readthedocs build to cause the build to succeed without any generated documentation making it into the output.

**Comment by adamnovak** [comment]
It looks like the last working docs build on ReadTheDocs was https://readthedocs.org/projects/bdsg/builds/10701772/, and as of https://readthedocs.org/projects/bdsg/builds/10727470/ our builds started warning that they can't import the bdsg module.

**Comment by adamnovak** [comment]
The underlying problem is that ReadTheDocs provides several installed versions of Python, and CMake is choosing to build the module for a different version of Python than the one ReadTheDocs is actually running the doc generation under.
