### ISSUE TITLE
Question on extracted path with bdsg

### ISSUE THREAD

**Issue by RenzoTale88** [vgteam/libbdsg#92]
Hello,
I'm trying to write a script that extract the genome-specific sequences using bdsg in python as suggested here [https://github.com/vgteam/vg/issues/3153](url). I've managed to load a pg graph, extract the paths in there and separate the paths from the reference genome from the others:
```
pg = bdsg.bdsg.PackedGraph()
pg.deserialize( 'ingenome.pg' )
node_count = pg.get_node_count()
edge_count = pg.get_edge_count()
path_count = pg.get_path_count()

print('Found:')
print( ' - {} nodes\n - {} edges\n - {} paths'.format( node_count, edge_count, path_count ) )

# Get paths
path_handle = []
pg.for_each_path_handle(lambda y: path_handle.append(y) or True)
path_names = [pg.get_path_name(i) for i in path_handle ]

# Get target paths
target_paths = [ i for i in path_names if args.target_genome in i ]
target_path_handle = [ i for i in path_handle if args.target_genome in pg.get_path_name(i) ]

# Get query paths
query_paths = [ i for i in path_names if args.target_genome in i ]
query_path_handle = [ i for i in path_handle if args.target_genome in pg.get_path_name(i) ]

```

I've also seen that I can extract the nodes in a path of interest using the approach:
```
handles = []
pg.for_each_step_in_path(query_path_handle[0], lambda y: handles.append(pg.get_handle_of_step(y)) or True)
```
And their ids with:
```
nodes_ids = [pg.get_id(i) for i in handles]
```

My question is pretty straightforward: am I right that the list of nodes generated by ```for_each_step_in_path()``` is ordered by position in the path? So that the first element in the list is the first node and therefore the initial position is 0, whereas the second node will be 0 plus the sum of the preceeding nodes' length.

Thanks in advance
Andrea

**Comment by jeizenga** [comment]
Yes, you are correct. The handles will always be iterated over in order.
